# Default configuration
default_conf: configs/default_config.yaml

# Instance params
instance_path: instances/eternity_trivial_A.txt
reward_type: 'delta'
reward_penalty: 0.00
curriculum_learning: True
manual_orient: True

# Training parameters
group: Curriculum - 4
batch_size: 256
lr: 3.0e-4
total_timesteps: 1.0e7  # Total steps for training each env
gamma: 0.7
gae_lambda: 0.6

# Model parameters
load_pretrain: # Keep empty for no pretraining
net_arch:
  hidden_size: 100
  cnn_layers: 1
  n_heads: 5
  ff_size: 200
  dropout: 0.1
  n_layers: 5
  const_term_encoding: 100.0
