# Default configuration
default_conf: configs/default_config.yaml

# Instance params
instance_path: instances/eternity_trivial_A.txt
reward_type: 'delta'
reward_penalty: 0.0
curriculum_learning: True

# Training parameters
group: Curriculum - \#1
batch_size: 256
lr: 2.0e-4
total_timesteps: 1.0e7  # Total steps for training each env

# Model parameters
load_pretrain: # Keep empty for no pretraining
net_arch:
  hidden_size: 30
  cnn_layers: 2
  n_heads: 5
  ff_size: 100
  dropout: 0.1
  n_layers: 5
