# Instance params
instance_path: instances/eternity_A.txt
max_steps: 16
manual_orient: false
reward_type: 'win_ratio'
reward_penalty: 0.1

# Training parameters
group: Medium size - no pretraining
batch_size: 256
lr: 1.0e-4
gamma: 0.99
total_timesteps: 1.0e5  # Total steps for training
n_steps: 2048  # How many steps between each rollouts
seed: 1
num_cpu: 6

# Model parameters
load_pretrain: # models/c5vpn43n  # Keep empty for no pretraining
net_arch:
  hidden_size: 10
  cnn_layers: 1
  n_heads: 1
  ff_size: 50
  dropout: 0.1
  n_layers: 5
