# Instance params
instance_path: instances/eternity_A.txt
max_steps: 50
manual_orient: false
reward_type: 'win_ratio'
reward_penalty: 0.0

# Training parameters
group: Test
batch_size: 256
lr: 4.0e-4
gamma: 0.99
clip_range: 0.2
normalize_advantage: True
ent_coef': 0.0
vf_coef: 0.5
gae_lambda: 0.95
total_timesteps: 2.0e5  # Total steps for training
n_steps: 2048  # How many steps between each rollouts
seed: 1
num_cpu: 6

# Model parameters
load_pretrain: # models/c5vpn43n  # Keep empty for no pretraining
net_arch:
  hidden_size: 10
  cnn_layers: 1
  n_heads: 1
  ff_size: 50
  dropout: 0.1
  n_layers: 5
