# Instance params
instance_path: instances/eternity_trivial_A.txt
max_steps: 50
manual_orient: false
reward_type: 'delta'
reward_penalty: 0.0
curriculum_learning: True

# Training parameters
group: Sweep - Reward type - trivial B
batch_size: 256
lr: 2.0e-4
gamma: 0.99
total_timesteps: 1.0e6  # Total steps for training
n_steps: 2048  # How many steps between each rollouts
seed: 0
num_cpu: 6

# Model parameters
load_pretrain: # Keep empty for no pretraining
net_arch:
  hidden_size: 10
  cnn_layers: 1
  n_heads: 1
  ff_size: 50
  dropout: 0.1
  n_layers: 5
