# Default configuration
default_conf: configs/default_config.yaml

# Instance params
instance_path: instances/eternity_trivial_A.txt
reward_type: 'delta'
reward_penalty: 0.0
manual_orient: True

# Training parameters
group: Trivial env
# group: Sweep - trivial - A const term encoding
batch_size: 256
lr: 1.0e-4
total_timesteps: 1.0e7  # Total steps for training
gae_lambda: 0.6

# Model parameters
load_pretrain: # Keep empty for no pretraining
net_arch:
  hidden_size: 100
  cnn_layers: 1
  n_heads: 5
  ff_size: 200
  dropout: 0.1
  n_layers: 5
  const_term_encoding: 1.0
